// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRJ142BkArLjYs5VLtnfofxjZwVK-7fW8',
    appId: '1:154870925999:web:70b56635d505332576e25a',
    messagingSenderId: '154870925999',
    projectId: 'api-teste-fa910',
    authDomain: 'api-teste-fa910.firebaseapp.com',
    databaseURL: 'https://api-teste-fa910-default-rtdb.firebaseio.com',
    storageBucket: 'api-teste-fa910.appspot.com',
    measurementId: 'G-39ZGPEZE0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByr4fdMuYONZmM0Y3bSzLeEFx9WzIBn9I',
    appId: '1:154870925999:android:82081db24cbf32a276e25a',
    messagingSenderId: '154870925999',
    projectId: 'api-teste-fa910',
    databaseURL: 'https://api-teste-fa910-default-rtdb.firebaseio.com',
    storageBucket: 'api-teste-fa910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcBSi0cdLLvdibHM-D8s54zhfqJeZyew',
    appId: '1:154870925999:ios:cdfe084302c0971b76e25a',
    messagingSenderId: '154870925999',
    projectId: 'api-teste-fa910',
    databaseURL: 'https://api-teste-fa910-default-rtdb.firebaseio.com',
    storageBucket: 'api-teste-fa910.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkcBSi0cdLLvdibHM-D8s54zhfqJeZyew',
    appId: '1:154870925999:ios:cdfe084302c0971b76e25a',
    messagingSenderId: '154870925999',
    projectId: 'api-teste-fa910',
    databaseURL: 'https://api-teste-fa910-default-rtdb.firebaseio.com',
    storageBucket: 'api-teste-fa910.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRJ142BkArLjYs5VLtnfofxjZwVK-7fW8',
    appId: '1:154870925999:web:c98438460b8ea68676e25a',
    messagingSenderId: '154870925999',
    projectId: 'api-teste-fa910',
    authDomain: 'api-teste-fa910.firebaseapp.com',
    databaseURL: 'https://api-teste-fa910-default-rtdb.firebaseio.com',
    storageBucket: 'api-teste-fa910.appspot.com',
    measurementId: 'G-2J18VEW8F4',
  );
}
